export const CONFIRMATION_BOTTOM_DRAWER_DEFAULT_STATE = 'CONFIRMATION_BOTTOM_DRAWER_DEFAULT_STATE';
export const CONFIRMATION_BOTTOM_DRAWER_LOADING_STATE = 'CONFIRMATION_BOTTOM_DRAWER_LOADING_STATE';
export const CONFIRMATION_BOTTOM_DRAWER_FINISHED_STATE =
    'CONFIRMATION_BOTTOM_DRAWER_FINISHED_STATE';
