export const COURSE_BADGE_BESTSELLER = 'bestseller';
export const COURSE_BADGE_FREE = 'free'; // not currently a badge family
export const COURSE_BADGE_HIGHEST_RATED = 'top_rated';
export const COURSE_BADGE_HOT_AND_NEW = 'hot_and_new';
export const COURSE_BADGE_NEW = 'new';
export const COURSE_BADGE_UPDATED_RECENTLY = 'updated_recently';
export const COURSE_BADGE_CODING_EXERCISES = 'coding_exercises';
export const ASSESSMENT_BADGE_IN_PROGRESS = 'progress';
export const ASSESSMENT_BADGE_COMPLETED = 'completed';
export const ASSESSMENT_BADGE_EXPIRED = 'expired';
