/**
 * The available names of the expressive icons.
 */
export const ExpressiveIconName = [
    '24-7',
    'ai',
    'approachable-content',
    'assessment-quiz',
    'assessment-test',
    'breadth',
    'capstone-events',
    'captions',
    'certificate',
    'challenge-1',
    'challenge-2',
    'change-management',
    'choosing-hand',
    'clock',
    'co-hort',
    'communication',
    'conflict-management',
    'content',
    'course-builder',
    'course-ratings',
    'data-1',
    'data-2',
    'data-science',
    'dei',
    'desktop',
    'devops',
    'digital-transformation',
    'empty-state-1',
    'empty-state-2',
    'esg',
    'executive-briefing',
    'global-1',
    'global-2',
    'hands-on-learning',
    'hands-on-practice',
    'hobby',
    'hr',
    'hybrid-workforce',
    'impact-measurement',
    'instructor',
    'integration-1',
    'integration-2',
    'integration-3',
    'language-1',
    'language-2',
    'language-change',
    'leadership',
    'leading-high-performance-teams',
    'leading-through-change',
    'learner',
    'learning-delivery',
    'learning-guide',
    'learning-labs',
    'learning-path',
    'learning-together',
    'marketing',
    'mental-health',
    'mentor',
    'micro-learning',
    'mobile',
    'new-manager',
    'new',
    'observer',
    'on-demand-1',
    'on-demand-2',
    'operations-management',
    'organizations-1',
    'organizations-2',
    'padlock',
    'payment',
    'play',
    'privacy',
    'product-management',
    'productivity',
    'project-management',
    'qa',
    'quality',
    'relevance-1',
    'relevance-2',
    'remote-work',
    'researcher',
    'resources',
    'retention-1',
    'retention-2',
    'roi',
    'role-model',
    'rookie-plant',
    'rookie',
    'sales-target',
    'security',
    'signs',
    'smart-tips',
    'soft-skills',
    'storytelling',
    'streak-empty-state',
    'streak-flame',
    'subscription',
    'talent-management',
    'team-training-1',
    'team-training-2',
    'trailblazer',
    'translate-1',
    'translate-2',
    'traveler',
    'users',
    'visionary',
] as const;

/**
 * A Mapping of Expressive Icon name and its corresponding filename.
 *
 * @remarks
 * We use a map here in case the filename or filetype changes in the future.
 */
export const ExpressiveIconFileMap = new Map<typeof ExpressiveIconName[number], string>([
    ['24-7', '24-7.png'],
    ['ai', 'ai.png'],
    ['approachable-content', 'approachable-content.png'],
    ['assessment-quiz', 'assessment-quiz.png'],
    ['assessment-test', 'assessment-test.png'],
    ['breadth', 'breadth.png'],
    ['capstone-events', 'capstone-events.png'],
    ['captions', 'captions.png'],
    ['certificate', 'certificate.png'],
    ['challenge-1', 'challenge-1.png'],
    ['challenge-2', 'challenge-2.png'],
    ['change-management', 'change-management.png'],
    ['choosing-hand', 'choosing-hand.png'],
    ['clock', 'clock.png'],
    ['co-hort', 'co-hort.png'],
    ['communication', 'communication.png'],
    ['conflict-management', 'conflict-management.png'],
    ['content', 'content.png'],
    ['course-builder', 'course-builder.png'],
    ['course-ratings', 'course-ratings.png'],
    ['data-1', 'data-1.png'],
    ['data-2', 'data-2.png'],
    ['data-science', 'data-science.png'],
    ['dei', 'dei.png'],
    ['desktop', 'desktop.png'],
    ['devops', 'devops.png'],
    ['digital-transformation', 'digital-transformation.png'],
    ['empty-state-1', 'empty-state-1.png'],
    ['empty-state-2', 'empty-state-2.png'],
    ['esg', 'esg.png'],
    ['executive-briefing', 'executive-briefing.png'],
    ['global-1', 'global-1.png'],
    ['global-2', 'global-2.png'],
    ['hands-on-learning', 'hands-on-learning.png'],
    ['hands-on-practice', 'hands-on-practice.png'],
    ['hobby', 'hobby.png'],
    ['hr', 'hr.png'],
    ['hybrid-workforce', 'hybrid-workforce.png'],
    ['impact-measurement', 'impact-measurement.png'],
    ['instructor', 'instructor.png'],
    ['integration-1', 'integration-1.png'],
    ['integration-2', 'integration-2.png'],
    ['integration-3', 'integration-3.png'],
    ['language-1', 'language-1.png'],
    ['language-2', 'language-2.png'],
    ['language-change', 'language-change.png'],
    ['leadership', 'leadership.png'],
    ['leading-high-performance-teams', 'leading-high-performance-teams.png'],
    ['leading-through-change', 'leading-through-change.png'],
    ['learner', 'learner.png'],
    ['learning-delivery', 'learning-delivery.png'],
    ['learning-guide', 'learning-guide.png'],
    ['learning-labs', 'learning-labs.png'],
    ['learning-path', 'learning-path.png'],
    ['learning-together', 'learning-together.png'],
    ['marketing', 'marketing.png'],
    ['mental-health', 'mental-health.png'],
    ['mentor', 'mentor.png'],
    ['micro-learning', 'micro-learning.png'],
    ['mobile', 'mobile.png'],
    ['new-manager', 'new-manager.png'],
    ['new', 'new.png'],
    ['observer', 'observer.png'],
    ['on-demand-1', 'on-demand-1.png'],
    ['on-demand-2', 'on-demand-2.png'],
    ['operations-management', 'operations-management.png'],
    ['organizations-1', 'organizations-1.png'],
    ['organizations-2', 'organizations-2.png'],
    ['padlock', 'padlock.png'],
    ['payment', 'payment.png'],
    ['play', 'play.png'],
    ['privacy', 'privacy.png'],
    ['product-management', 'product-management.png'],
    ['productivity', 'productivity.png'],
    ['project-management', 'project-management.png'],
    ['qa', 'qa.png'],
    ['quality', 'quality.png'],
    ['relevance-1', 'relevance-1.png'],
    ['relevance-2', 'relevance-2.png'],
    ['remote-work', 'remote-work.png'],
    ['researcher', 'researcher.png'],
    ['resources', 'resources.png'],
    ['retention-1', 'retention-1.png'],
    ['retention-2', 'retention-2.png'],
    ['roi', 'roi.png'],
    ['role-model', 'role-model.png'],
    ['rookie-plant', 'rookie-plant.png'],
    ['rookie', 'rookie.png'],
    ['sales-target', 'sales-target.png'],
    ['security', 'security.png'],
    ['signs', 'signs.png'],
    ['smart-tips', 'smart-tips.png'],
    ['soft-skills', 'soft-skills.png'],
    ['storytelling', 'storytelling.png'],
    ['streak-empty-state', 'streak-empty-state.png'],
    ['streak-flame', 'streak-flame.png'],
    ['subscription', 'subscription.png'],
    ['talent-management', 'talent-management.png'],
    ['team-training-1', 'team-training-1.png'],
    ['team-training-2', 'team-training-2.png'],
    ['trailblazer', 'trailblazer.png'],
    ['translate-1', 'translate-1.png'],
    ['translate-2', 'translate-2.png'],
    ['traveler', 'traveler.png'],
    ['users', 'users.png'],
    ['visionary', 'visionary.png'],
]);
