export const LEAVE_A_RATING_MY_COURSES_LOCATION = 'my_courses';
export const LEAVE_A_RATING_DASHBOARD_LOCATION = 'dashboard';

export const NON_COURSE_TAKING_LOCATIONS = [
    LEAVE_A_RATING_MY_COURSES_LOCATION,
    LEAVE_A_RATING_DASHBOARD_LOCATION,
];
