'use strict';

// Autogenerated file through: 'babel-external-helpers > webpack/babel/external-helpers.js'
require('./external-helpers');

require('core-js/stable');
require('regenerator-runtime/runtime');
